version: "3"
services:
  wenet_profile_manager_database:
    image: mongo:4.2.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: wenetProfileManagerDB
    volumes:
      - ./initialize-wenetProfileManagerDB.js:/docker-entrypoint-initdb.d/init-mongo.js
      - wenet_profile_manager_data:/data/db
    networks:
      wenet_interaction_protocol_engine_net:

  wenet_profile_manager_api:
    image: wenet/profile-manager:0.10.0
    depends_on:
      - wenet_profile_manager_database
    environment:
      DB_HOST: wenet_profile_manager_database
      WAIT_HOSTS: wenet_profile_manager_database:27017
    ports:
      - ${PROFILE_MANAGER_API_PORT:-8080}:8080
    networks:
      wenet_interaction_protocol_engine_net:

  wenet_task_manager_database:
    image: mongo:4.2.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: wenetTaskManagerDB
    volumes:
      - ./initialize-wenetTaskManagerDB.js:/docker-entrypoint-initdb.d/init-mongo.js
      - wenet_task_manager_data:/data/db
    networks:
      wenet_interaction_protocol_engine_net:

  wenet_task_manager_api:
    image: wenet/task-manager:0.2.0
    depends_on:
      - wenet_task_manager_database
    environment:
      DB_HOST: wenet_task_manager_database
      WAIT_HOSTS: wenet_task_manager_database:27017
    ports:
      - ${TASK_MANAGER_API_PORT:-8081}:8080
    networks:
      wenet_interaction_protocol_engine_net:

  database:
    image: mongo:4.2.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: wenetInteractionProtocolEngineDB
    networks:
      wenet_interaction_protocol_engine_net:
    volumes:
      - ./initialize-wenetInteractionProtocolEngineDB.js:/docker-entrypoint-initdb.d/init-mongo.js
      - wenet_interaction_protocol_engine_data:/data/db

  api:
    build:
      context: ../../../.
      dockerfile: src/main/docker/Dockerfile
    image: "wenet/interaction-protocol-engine"
    depends_on:
      - database
    networks:
      wenet_interaction_protocol_engine_net:
    ports:
      - ${API_PORT:-80}:8080
    environment:
      DB_HOST: database
      WENET_PROFILE_MANAGER_API_HOST: wenet_profile_manager_api
      WENET_PROFILE_MANAGER_API_PORT: 8080
      WENET_PROFILE_MANAGER_API_PATH: ""
      WENET_TASK_MANAGER_API_HOST: wenet_task_manager_api
      WENET_TASK_MANAGER_API_PORT: 8081
      WENET_TASK_MANAGER_API_PATH: ""
      WAIT_HOSTS: database:27017, wenet_profile_manager_api:8080, wenet_task_manager_api:8081

volumes:
    wenet_interaction_protocol_engine_data:
    wenet_profile_manager_data:

networks:
    wenet_interaction_protocol_engine_net:
