version: "3"
services:
  wenet_interaction_protocol_engine_database:
    image: mongo:4.2.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: wenetInteractionProtocolEngineDB
    volumes:
      - ./initialize-wenetInteractionProtocolEngineDB.js:/docker-entrypoint-initdb.d/init-mongo.js
      - wenet_interaction_protocol_engine_data:/data/db
    networks:
      wenet_network:

  wenet_interaction_protocol_engine_api:
    image: wenet/interaction_protocol_engine:latest
    restart: always
    depends_on:
      - wenet_interaction_protocol_engine_database
    environment:
      DB_HOST: wenet_interaction_protocol_engine_database
      WENET_PROFILE_MANAGER_API: ${WENET_PROFILE_MANAGER_API:-"https://wenet.u-hopper.com/prod/profile_manager"}
      WENET_TASK_MANAGER_API: ${WENET_TASK_MANAGER_API:-"https://wenet.u-hopper.com/prod/task_manager"}
      WENET_SERVICE_API: ${WENET_SERVICE_API:-"https://wenet.u-hopper.com/prod/service"}
      WENET_INCENTIVE_SERVER_API: ${WENET_ICENTIVE_SERVER_API:-"https://wenet.u-hopper.com/prod/incentive_server"}
      WENET_SOCIAL_CONTEXT_BUILDER_API: ${WENET_SOCIAL_CONTEXT_BUILDER_API:-"https://wenet.u-hopper.com/prod/social_context_builder"}
      WAIT_HOSTS: wenet_interaction_protocol_engine_database:27017
    networks:
      wenet_network:
    ports:
      - ${INTERACTION_PROTOCOL_ENGINE_API_PORT:-8083}:8080


volumes:
    wenet_interaction_protocol_engine_data:

networks:
    wenet_network:
